### ISSUE TITLE
Prioritization (Curran's TODOs)

### ISSUE THREAD

**Issue by curran** [nuagenetworks/visualization-framework#155]
* [x] Navigation between dashboard pages #23
* [x] Support fixed wight ribbons #153 (PR #159)
* [x] Tabify hits #166 (PR #164)
* [x] Support click navigation in all visualization components #152
* [x] #152 / Support click navigation in Chord Diagram #160 (PR #164)
* [x] #152 / Support click navigation in Pie Chart #161 (PR #165)
* [x] #152 / Support click navigation in Simple Text Graph #162 (PR  #171)
* [x] Table sizing #101 (PR #180)
* [x] Multiple template parsing in a single string #197
* [x] Multiple line in line chart #185
* [x] Make stroke configurable for Bar Chart #177
* [x] Chord Diagram Improvements #143
* [x] Add configuration option for tick format #134 (PR #187)
* [x] Add configuration option for tick mark density #133 (PR #187)
* [x] JSON Templates Improvement https://github.com/curran/json-templates/issues/2
* [x] floating value should be limited to 2 decimal points #174
* [x] set timestamp to yy:mm:dd:mm:ss in chord table #172 and
* [x] Y-axis and X-axis labels #189
* [x] Integrating SimpleTextGraph with tabify results #140 (reassigned to @t00f )
* [x] Table should handle object response along with key values #224
* [x] Pie-Chart Variants/Improvements #144
* [x] #144 / Add a configuration option for the distance of labels from the center (`pieLabelRadius`)
* [x] #144 / Add a configuration option for showing percentage as text.
* [x] #144 / Add a color legend, part of more general **Color Legends** #200
* [x] #138 / Tooltips for Bar Graph #207
* [x] #138 / Tooltips for Pie Graph #208
* [x] #138 / Tooltips for Chord Diagram #211
* [x] #138 / Tooltips for Table Graph #209 
* [x] Handle hits within agg in tabify #281
* [x] Create dashboard examples #78
* [x] Core Framework Tasks #77
* [x] Tooltips for diagrams #138
* [x] #138 / Tooltips for Line Graph #210
* [x] Add brushing to Line Graph #150 
* [ ] Show circle on hover in Line Chart #345 (required to pair with brushing feature)
* [ ] Enable the use of colorColumn in Chord Diagram #231
* [ ] Stacked bar chart #142
* [ ] Pagination for Tables #130 
* [ ] Gauge chart #154
* [ ] Long axis labels should be wrapped #288
