### ISSUE TITLE
VSS Task List

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#422]
Anil's Items:

- [x] remove dashboard name out of the header and highlight the relevant menu item for the dashboard in the menu bar

- [x] top menu item font size - make is larger so it is easy to know where the user is currently
use icons from VSD GUI for Enterprise, domains, zones, Events, ACLs etc. (in a way similar to current VSD GUI)

- [x] pagination for all tables

- [x] No UUIDs in any of the main dashboard tables 

- [x] Charts must be embeddable in 3rd party portals 

- [ ] if there is no elastic search host connection - instead of showing "oops no active Elastic host" (see screenshot below) in each of the charts in various pages - is there a way to display a page that says a simple message "Unable to connect to  ElasticSearch datastore." and similarly for VSD "Unable to connect to  VSD datastore."

Main menu bar

- [x] replace “VSS Visualizations” with “VSS Analytics” 

- [x] Each enterprise has enterprise icons

Enterprise Dashboard page 

- [x] replace “VSS Dashboard - <Enterprise name>” with “Enterprise icon <Enterprise name>”

Domain - Event Analytics page

- [ ] Event dashboard shows all events, which can be further filtered by event type

Domain - Traffic analytics page

- [ ]  ICMP vs time - x-axis needs to show time (it seems to display something else instead now).
 

 Ronak's items:
- [ ]  show logged in user in  all the pages (ideally consistent with VSD GUI)

Enterprise Dashboard page 

- [x] replace “Top security events” with “Top 5 security events”
- [x] replace “TCA Alerts” with “Alerts”
- [x] replace “Events” with “Security Events”

Enterprise - New Menu item - Flow Analytics

- [ ] Can we add a menubar item which has current “Dashboard” as one of the items (highlighted by default) and in addition have a "Flow Analytics" menu item at the Enterprise Level. Selecting “Flow Analytics” at Enterprise level shows traffic between various L2/L3 domains in the Enteprise (the page should also have filters for src domain and dst domain)?  Each flow in the flow table for this can show all the meta-data for the flow from VSD including src/dst domain, src/dst zone, src/dst PG, along with time stamp, ACL action etc.

Domain - ACL analytics page

- [ ] remove ACL ID in top 5 ACL chart and replace with number (1..5) that is hyperlinked to show ACL detail info

Domain - Event Analytics page

- [ ] replace vPortuuid with Src IP

Domain - Flow analytics page

- [x] add Any in Src and Dst PG option  (use “any to any” as default)
shows flow details table by default (for any to any option) underneath the chord chart for a domain rather than requiring user to select a chord in flow visualization chord diagram

**Comment by minimilk** [comment]
Default option for Source and Destination field should be Any to Any.
![any-src-dest](https://user-images.githubusercontent.com/9605878/33961719-ea45dce4-e003-11e7-9f6f-8c2e237e975e.png)

**Comment by minimilk** [comment]
Attempting to display enterprise icon returns 404
![icon-gone](https://user-images.githubusercontent.com/9605878/33968757-8361b3b6-e01e-11e7-9772-b533d5b7430b.png)

**Comment by nxanil** [comment]
@minimilk @ronakmshah 

ICON issue has been resolved in PR #549

Also, PG is set as default option. Let me know if you want to change it to ANY

**Comment by minimilk** [comment]
Icon issue has been solved in vssui-master-cur-13e32f.

![total-4](https://user-images.githubusercontent.com/9605878/34023271-cb296060-e0f8-11e7-9618-a030d4ccbb60.png)

**Comment by minimilk** [comment]
@nxanil - The team seems still want PG to PG after discussion. Let's keep as-is for now. Thanks for checking!
