### ISSUE TITLE
AAR Todo list

### ISSUE THREAD

**Issue by bharat-mukheja** [nuagenetworks/visualization-framework#641]
Creating a list of Todo's in terms of their priority. Anyone can add to it. These are not necessarily all required, but not all of them unrequired as well. I know there is already a list by Curran, but this deals more with the UX perspective than backend. Will keep on adding more as they appear.

* [x] Implement a styling in the 'i' detail part of the viz. https://github.com/nuagenetworks/visualization-framework/issues/640
* [ ] Fix table headers https://github.com/nuagenetworks/visualization-framework/issues/648
* [ ] Fix margins and axis alignment https://github.com/nuagenetworks/visualization-framework/issues/650
