### ISSUE TITLE
Core Framework Tasks

### ISSUE THREAD

**Issue by curran** [nuagenetworks/visualization-framework#77]
- [x] Resizing (Chris + Curran)
  - [x] In dashboard case (including resize with react-grid-layout) #82
  - [x] Route to visualization case
- [x] Components Part I (Curran)
  - [x] Vertical Bar Chart
  - [x] Simple Text Graph
  - [x] Table #70
  - [x] Horizontal Bar Chart (target Oct. 14) #88
  - [x] Date Histogram (target Oct. 14)
  - [x] Line Chart (target Oct. 14) #96
  - [x] Simple Text Graph With Circle (target Oct. 14) #99 
- [x] Pie Chart / Donut Chart #119
- [x] Nested Aggs in Tabify #106
- [x] Dashboards (Curran + Ronak) #78 
- [x] Chord Diagram #131
- [x] Clicking/Navigation (Curran) #23
- [ ] [Guage Chart](http://c3js.org/samples/chart_gauge.html) #154
- [ ] Testing (Chris)
  - [x] State, actions, reducers
  - [ ] React components - DOM rendering
- [ ] Split to an Open Source (Chris)
- [x] VSD Integration (Chris)
- [x] Theming/Skinning - Needs to have similar look and feel to VSD UI
  - [x] Colors (Chris)
  - [x] Fonts (Chris)
  - [x] Font sizes (Chris)
  - [x] Graphs styling (Curran)
- [ ] Geo Graph
